# Generated by Django 4.1 on 2022-09-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='king',
            new_name='kind',
        ),
    ]
